# Generated by Django 5.0.4 on 2024-07-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_total_sales_ordersstatistics_average_order_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdersStatistics',
        ),
    ]
