# Generated by Django 4.2.13 on 2024-07-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='All Branches', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Company Name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('...', '...'), ('Education', 'Education'), ('Medical', 'Medical'), ('Restaurants & Cafes', 'Restaurants & Cafes'), ('Health & Fitness', 'Health & Fitness'), ('Home Services', 'Home Services'), ('Financial Services', 'Financial Services'), ('Pet Services', 'Pet Services'), ('Automotive', 'Automotive'), ('Travel & Hospitality', 'Travel & Hospitality'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Fashion', 'Fashion'), ('Other', 'Other')], default='...', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.city'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.company'),
        ),
    ]
