# Generated by Django 4.2.13 on 2024-08-21 18:30

from django.db import migrations
from django.conf import settings

def set_default_created_by(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Product = apps.get_model('products', 'Product')
    default_user = User.objects.first()
    if default_user:
        Product.objects.filter(created_by__isnull=True).update(created_by=default_user)



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_created_by'),
    ]

    operations = [
        migrations.RunPython(set_default_created_by),
    ]
