# Generated by Django 5.0.4 on 2024-04-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employes_newuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.newuser',),
        ),
        migrations.AddField(
            model_name='employes',
            name='company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
