# Generated by Django 5.0.4 on 2024-04-25 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_employes_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='company name')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='address')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='phone')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.newuser',),
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='employes',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='employes',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='employes',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='employes',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('employe', 'Employe'), ('company', 'Company'), ('trader', 'Trader')], default='user', max_length=50, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='user name'),
        ),
    ]
