# Generated by Django 5.0.4 on 2024-04-25 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True, verbose_name='user name')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('employe', 'Employe'), ('company', 'Company'), ('trader', 'Trader')], default='user', max_length=50, verbose_name='Role')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='company name')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='address')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='phone')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.newuser',),
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='company name')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='address')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='phone')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.newuser',),
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='address')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='phone')),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.newuser',),
        ),
    ]
