# Generated by Django 5.0.4 on 2024-04-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='employes',
            name='company',
        ),
        migrations.DeleteModel(
            name='Trader',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employes',
        ),
    ]
